
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'A4D0E60CB9E0C51D9BE40F4CCB5B7887'
    
_lr_action_items = {'WORD':([10,11,12,13,14,18,19,20,21,22,23,26,27,29,],[-17,-6,-17,-7,19,-12,-14,-17,-13,-16,-15,-8,-17,-11,]),'SEMICOLON':([10,11,12,13,14,15,17,18,19,20,21,22,23,25,26,27,28,29,],[-17,-6,-17,-7,-9,24,26,-12,-14,-17,-13,-16,-15,-10,-8,-17,29,-11,]),'OBRACE':([7,10,11,12,13,14,18,19,20,21,22,23,26,27,29,],[10,-17,-6,-17,-7,20,-12,-14,-17,-13,-16,-15,-8,-17,-11,]),'ZONETOK':([0,1,2,4,5,9,24,],[-17,3,-1,-2,-3,-4,-5,]),'EBRACE':([10,12,13,20,26,27,],[-17,15,-7,-17,-8,28,]),'QUOTE':([3,8,10,11,12,13,14,16,18,19,20,21,22,23,26,27,29,],[6,11,-17,-6,-17,-7,6,6,-12,-14,-17,-13,-16,-15,-8,-17,-11,]),'FILENAME':([6,],[8,]),'FILETOK':([10,12,13,20,26,27,],[-17,16,-7,-17,-8,16,]),'$end':([0,1,2,4,5,9,24,],[-17,0,-1,-2,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'commands':([0,],[1,]),'statements':([12,27,],[14,14,]),'zonecontent':([7,],[9,]),'zonestatements':([10,20,],[12,27,]),'command':([1,],[4,]),'block':([14,],[23,]),'statement':([14,],[21,]),'zonestatement':([12,27,],[17,17,]),'zone_set':([1,],[5,]),'quotename':([3,14,16,],[7,22,25,]),'empty':([0,10,12,20,27,],[2,13,18,13,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> commands","S'",1,None,None,None),
  ('commands -> empty','commands',1,'p_commands','exam5.py',46),
  ('commands -> commands command','commands',2,'p_commands','exam5.py',47),
  ('command -> zone_set','command',1,'p_command','exam5.py',53),
  ('zone_set -> ZONETOK quotename zonecontent','zone_set',3,'p_zoneset','exam5.py',57),
  ('zonecontent -> OBRACE zonestatements EBRACE SEMICOLON','zonecontent',4,'p_zonecontent','exam5.py',62),
  ('quotename -> QUOTE FILENAME QUOTE','quotename',3,'p_quotename','exam5.py',66),
  ('zonestatements -> empty','zonestatements',1,'p_zonestatements','exam5.py',70),
  ('zonestatements -> zonestatements zonestatement SEMICOLON','zonestatements',3,'p_zonestatements','exam5.py',71),
  ('zonestatement -> statements','zonestatement',1,'p_zonestatement','exam5.py',78),
  ('zonestatement -> FILETOK quotename','zonestatement',2,'p_zonestatement','exam5.py',79),
  ('block -> OBRACE zonestatements EBRACE SEMICOLON','block',4,'p_block','exam5.py',86),
  ('statements -> empty','statements',1,'p_statements','exam5.py',89),
  ('statements -> statements statement','statements',2,'p_statements','exam5.py',90),
  ('statement -> WORD','statement',1,'p_statement','exam5.py',94),
  ('statement -> block','statement',1,'p_statement','exam5.py',95),
  ('statement -> quotename','statement',1,'p_statement','exam5.py',96),
  ('empty -> <empty>','empty',0,'p_empty','exam5.py',103),
]
